- name: Create temporary directory for downloading repositories
  ansible.builtin.tempfile:
    state: directory
    suffix: git
  register: harvester
  tags:
    - dag-update
    - minimal-dag-update

- name: Clone kielipankki-nlf-harvester
  ansible.builtin.git:
    repo: "https://github.com/CSCfi/kielipankki-nlf-harvester.git"
    version: "{{ harvester_branch }}"
    dest: "{{ harvester.path }}/"
    clone: yes
  tags:
    - dag-update
    - minimal-dag-update

- name: Install required packages for harvester
  ansible.builtin.pip:
    requirements: "{{ harvester.path }}/requirements.txt"
  become: yes
  tags:
    - dag-update

- name: Install required Airflow packages for harvester pipeline
  ansible.builtin.pip:
    requirements: "{{ harvester.path }}/pipeline/requirements.txt"
  become: yes
  tags:
    - dag-update

- name: Copy dags and plugins from harvester to airflow directory
  ansible.builtin.copy:
    src: "{{ harvester.path }}/pipeline/{{ item }}/"
    dest: "{{ airflow_directory }}/{{ item }}/"
    remote_src: yes
  with_items:
    - dags
    - plugins
  tags:
    - dag-update
    - minimal-dag-update

- name: Copy harvester files to airflow plugins directory
  ansible.builtin.copy:
    src: "{{ harvester.path }}/harvester"
    dest: "{{ airflow_directory }}/plugins/"
    remote_src: yes
  tags:
    - dag-update
    - minimal-dag-update

- name: Restart Airflow services to ensure refreshing cached plugins when only updating DAGs
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - airflow-scheduler
    - airflow-dagprocessor
  become: yes
  tags:
    - never
    - dag-update
    - minimal-dag-update

- name: Create a file for restic environment variables
  template:
    src: restic_env.yaml.j2
    dest: /home/ubuntu/restic_env.yaml

- name: Copy Airflow variable file to remote
  template:
    src: airflow_variables.json.j2
    dest: /home/ubuntu/airflow_variables.json
  tags:
    - dag-update

- name: Register Airflow variables
  ansible.builtin.command:
    cmd: airflow variables import /home/ubuntu/airflow_variables.json
  tags:
    - dag-update

- name: Add private key for connecting to Puhti
  ansible.builtin.copy:
    dest: "{{ puhti_robot_ssh_key_path }}"
    mode: "0600"
    content: "{{ lookup('passwordstore', 'lb_passwords/airflow/private-key-robot_2006633_puhti', returnall=true) }}"

# The or-operator ("||") means that the latter part of the command (new
# connection creation) is only executed if the former (grepping for puhti_conn
# in pre-existing connections) fails (i.e. puhti_conn not found).
- name: Create SSH connection to Puhti if not already present
  ansible.builtin.shell: >
    airflow connections list | grep 'puhti_conn'
    ||
    airflow connections add 'puhti_conn'
    --conn-json '{{ puhti_conn_conf | to_json }}'

- name: Create HTTP connection to NLF if not already present
  ansible.builtin.shell: >
    airflow connections list | grep 'nlf_http_conn'
    ||
    airflow connections add 'nlf_http_conn'
    --conn-type 'http'
    --conn-host 'https://digi.kansalliskirjasto.fi/interfaces/OAI-PMH'
    --conn-schema 'HTTPS'
