---

- name: Install Postgres
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    update_cache: yes
  become: yes

- name: Install Python dependency for Postgres
  ansible.builtin.pip:
    name: psycopg2-binary
  become: yes

- name: Start and enable Postgres service
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: "Grant connection privileges for postgres and airflow users"
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/14/main/pg_hba.conf"
    contype: host
    databases: all
    method: trust
    users: ["postgres", "airflow"]
    create: true
    address: 127.0.0.1/32
  become: yes

- name: "Reload PostgreSQL configuration"
  systemd:
    name: postgresql
    state: reloaded
  become: yes

- name: Restart Postgres service
  service:
    name: postgresql
    state: restarted
  become: yes

- name: Set postgres user password
  community.postgresql.postgresql_user:
    name: postgres
    password: "{{ airflow_db_root_password }}"
    login_host: 127.0.0.1
  become: true
  become_user: postgres
  ignore_errors: yes  # this only succeeds if the password has not already been set

- name: "Create a Postgres database for Airflow"
  community.postgresql.postgresql_db:
    state: present
    name: "{{ airflow_db_name }}"
    login_user: postgres
    login_password: "{{ airflow_db_root_password }}"
    login_host: 127.0.0.1

- name: Create airflow database user
  community.postgresql.postgresql_user:
    name: "{{ airflow_db_user }}"
    password: "{{ airflow_db_password }}"
    state: present
    db: "{{ airflow_db_name }}"
    login_user: postgres
    login_password: "{{ airflow_db_root_password }}"
    login_host: 127.0.0.1

- name: Grant database privileges for airflow user
  community.postgresql.postgresql_privs:
    type: database
    database: "{{ airflow_db_name }}"
    role: "{{ airflow_db_user }}"
    privs: ALL
    login_user: postgres
    login_password: "{{ airflow_db_root_password }}"
    login_host: 127.0.0.1

- name: Initialize the database
  ansible.builtin.shell: airflow db init

- name: Create Airflow admin user
  ansible.builtin.shell: >
    airflow users create 
    --username {{ airflow_username }} 
    --password {{ airflow_password }} 
    --firstname {{ airflow_firstname }} 
    --lastname {{ airflow_lastname }} 
    --email {{ airflow_email }}
    --role Admin 
