---

- name: Add public SSH key to the HPC environment for the robot account
  ansible.posix.authorized_key:
    user: "{{ hpc_robot_user }}"
    key: "{{ lookup('passwordstore', hpc_robot_ssh_public_key_location) }}"
