"""
Zip-merging utilities for making publishable packages of NLF data.
"""

import tarfile
from zipfile import ZipFile


def update_zip_with_tars(zipfilename, tarfilenames):
    zipfile = ZipFile(zipfilename, mode="a")
    for tarfilename in tarfilenames:
        tar = tarfile.open(tarfilename)
        while True:
            tar_item = tar.next()
            if tar_item == None:
                break
            if not tar_item.isfile():
                # paths should be autogenerated in the zip
                continue
            iobuf = tar.extractfile(tar_item)
            zipfile.writestr(tar_item.name, iobuf.read())
        tar.close()
    zipfile.close()


if __name__ == "__main__":
    import os
    import sys
    import argparse

    argparser = argparse.ArgumentParser(
        prog="collect-to-zip",
        epilog="Optionally write additional source filenames to stdin",
    )
    argparser.add_argument("zipfilename", help="The target zip")
    argparser.add_argument("--dir", type=str, help="Scan directory for sources")
    argparser.add_argument(
        "--sourcelist", type=str, help="Read file for sources, or - for stdin"
    )
    argparser.add_argument("--verbose", action="store_true")
    args = argparser.parse_args()
    sourcepaths = []
    if args.sourcelist:
        if args.sourcelist == "-":
            while True:
                try:
                    sourcepaths.append(input().strip())
                except EOFError:
                    break
        else:
            sourcepaths += [line.strip() for line in open(args.sourcelist)]
    if os.path.isdir(args.dir):
        sourcepaths += [
            os.path.join(args.dir, f)
            for f in os.listdir(args.dir)
            if f.endswith(".zip") or f.endswith(".tar")
        ]

    if args.verbose:
        sys.stderr.write(f"Updating {args.zipfilename} with:\n")
        for source in sourcepaths:
            sys.stderr.write(f"  {source}\n")

    update_zip_with_tars(
        args.zipfilename, filter(lambda x: x.endswith(".tar"), sourcepaths)
    )
