---

- name: Install required packages
  ansible.builtin.apt:
    name:
      - pip
      - libpq-dev
      - nginx
      - ufw
    update_cache: yes
  become: yes

- name: Install Airflow
  ansible.builtin.pip:
    name: apache-airflow[async,postgres,google]==2.11.0
    extra_args: --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.11.0/constraints-3.10.txt"
  become: yes

- name: Create gunicorn log directory
  ansible.builtin.file:
    path: /var/log/gunicorn
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
